"""
cleanup_3_1_lite.py

Deletes evidence files (and matching patch MDs) generated by
gemini-3.1-flash-lite, so the pipeline can re-process those courses
with a different model. Preserves all earlier evidence/patch files
(e.g. those from gemini-3-flash-preview).

Usage:
    python masters_v2/scripts/cleanup_3_1_lite.py
"""

import json
import os
from pathlib import Path

BASE = Path(r"c:\Users\HP\OneDrive\Desktop\course_data")
EVIDENCE_DIR = BASE / "masters_v2" / "evidence"
PATCH_DIR = BASE / "masters_v2" / "masters"

TARGET_MODEL = "gemini-3.1-flash-lite"


def main():
    ev_files = []
    for d, _, fs in os.walk(EVIDENCE_DIR):
        for f in fs:
            if f.endswith(".json"):
                ev_files.append(Path(d) / f)

    print(f"Scanning {len(ev_files)} evidence files for model={TARGET_MODEL}...")

    deleted_ev = 0
    deleted_md = 0
    kept = 0
    errors = 0

    for fp in ev_files:
        try:
            with open(fp, encoding="utf-8") as fh:
                data = json.load(fh)
        except Exception as e:
            print(f"  [skip] {fp.name}: {e}")
            errors += 1
            continue

        if data.get("gemini_model") == TARGET_MODEL:
            # Map evidence path -> patch MD path
            # masters_v2/evidence/<college>/<file>.evidence.json
            # -> masters_v2/masters/<college>/<file>__patch.md
            rel = fp.relative_to(EVIDENCE_DIR)
            md_path = PATCH_DIR / rel.parent / rel.name.replace(".evidence.json", "__patch.md")

            try:
                os.remove(fp)
                deleted_ev += 1
            except Exception as e:
                print(f"  [error removing evidence] {fp}: {e}")
                errors += 1
                continue

            if md_path.exists():
                try:
                    os.remove(md_path)
                    deleted_md += 1
                except Exception as e:
                    print(f"  [error removing patch] {md_path}: {e}")
                    errors += 1
        else:
            kept += 1

    print()
    print(f"Deleted {deleted_ev} evidence files (model={TARGET_MODEL})")
    print(f"Deleted {deleted_md} matching patch MDs")
    print(f"Kept   {kept} earlier evidence files intact (other models)")
    if errors:
        print(f"Errors: {errors}")


if __name__ == "__main__":
    main()
